#!/bin/bash
# Generated by eta-mu.boundaries.claude/emit-hook-config! -- do not edit.
# Canonical event: tool/requested
exec node /home/err/spaces/muse/.claude/dist/claude-server.js --hook tool/requested
