(ns eta-mu.opencode.settings-test
  (:require [cljs.test :refer [deftest is testing]]
            [eta-mu.opencode.settings :as settings]))

(deftest deep-merge-maps-merge-values-replace
  (is (= {:a {:b 1 :c 2}}
         (settings/deep-merge {:a {:b 1}} {:a {:c 2}})))
  (is (= {:a [3]}
         (settings/deep-merge {:a [1 2]} {:a [3]})))
  (is (= {:a 2} (settings/deep-merge {:a {:b 1}} {:a 2}))))

(deftest merged-applies-in-order
  (is (= {:model "b" :lsp true}
         (settings/merged [{:model "a" :lsp true} {:model "b"}]))))

(deftest render-scalars
  (is (= "\"hi\"" (settings/render-value "hi")))
  (is (= "\"allow\"" (settings/render-value :allow)))
  (is (= "true" (settings/render-value true)))
  (is (= "null" (settings/render-value nil)))
  (is (= "42" (settings/render-value 42))))

(deftest render-escapes-strings
  (is (= "\"a\\\"b\\\\c\\nd\"" (settings/render-value "a\"b\\c\nd"))))

(deftest render-empty-collections
  (is (= "{}" (settings/render-value {})))
  (is (= "[]" (settings/render-value []))))

(deftest render-round-trips-through-json
  (let [value {:$schema "https://opencode.ai/config.json"
               :permission {:external_directory {"~/devel/**" :allow}}
               :skills {:paths ["~/.agents/skills"]}
               :lsp true
               :autoupdate false}
        parsed (js->clj (js/JSON.parse (settings/render-value value)))]
    (is (= {"$schema" "https://opencode.ai/config.json"
            "permission" {"external_directory" {"~/devel/**" "allow"}}
            "skills" {"paths" ["~/.agents/skills"]}
            "lsp" true
            "autoupdate" false}
           parsed))))

(deftest render-orders-top-level-keys
  (testing "$schema first, known keys in host order, unknown sorted after"
    (let [doc (settings/render-value {:provider {} :model "m"
                                      :$schema "s" :zzz 1 :aaa 2})
          idx #(.indexOf doc %)]
      (is (< (idx "\"$schema\"") (idx "\"model\"")))
      (is (< (idx "\"model\"") (idx "\"provider\"")))
      (is (< (idx "\"provider\"") (idx "\"aaa\"")))
      (is (< (idx "\"aaa\"") (idx "\"zzz\""))))))

(deftest render-jsonc-has-header
  (let [doc (settings/render-jsonc {:lsp true} {:source "~/.ημ/config/opencode"})]
    (is (re-find #"^// Generated by the eta-mu daemon from ~/.ημ/config/opencode" doc))
    (is (re-find #"\"lsp\": true" doc))))
