#!/usr/bin/env bash
# Generate a host target's ignored entry namespace before Shadow discovers the
# module graph, then build it with this checkout's pinned Shadow executable.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

usage() {
  printf 'Usage: %s <opencode-plugin|mcp-server|claude-server|all> [...]\n' "$0" >&2
}

fail() {
  printf '[muse host build] %s\n' "$*" >&2
  exit 64
}

if (($# == 0)); then
  usage
  exit 64
fi

if (($# > 1)); then
  for target in "$@"; do
    [[ "$target" != all ]] || fail "'all' cannot be combined with another target"
  done
fi

targets=("$@")
if [[ "${targets[0]}" == all ]]; then
  targets=(opencode-plugin mcp-server claude-server)
fi

# Validate the complete request before probing or invoking any build tool.
for target in "${targets[@]}"; do
  case "$target" in
    opencode-plugin|mcp-server|claude-server) ;;
    *)
      usage
      fail "unsupported target: $target"
      ;;
  esac
done

command -v clojure >/dev/null 2>&1 || fail "missing prerequisite: clojure"
command -v node >/dev/null 2>&1 || fail "missing prerequisite: node"

shadow="$repo_root/node_modules/.bin/shadow-cljs"
[[ -x "$shadow" ]] || fail "missing pinned Shadow executable; run npm ci first"

# The generic MCP and Claude targets both publish to .mcp.json. Their build
# hooks each own a complete one-server document, so every MCP-producing request
# must preserve registrations that are not rebuilt, accumulate the documents
# generated by this request, publish their union after each build, and keep a
# target-to-registration ownership map so a rebuilt target can retire its old
# name even when both its name and registration payload change.
mcp_target_count=0
for target in "${targets[@]}"; do
  case "$target" in
    mcp-server|claude-server)
      mcp_target_count=$((mcp_target_count + 1))
      ;;
  esac
done

mcp_registry=""
generated_mcp_registry=""
mcp_generated_output=""
mcp_ownership=""
mcp_original_registry=""
mcp_original_ownership=""
mcp_original_registry_present=0
mcp_original_ownership_present=0
mcp_state_restore_ready=0
mcp_ownership_file="$repo_root/.muse-host-targets-owners.json"
mcp_lock_dir="$repo_root/.muse-host-targets.lock"
mcp_lock_owner="$mcp_lock_dir/owner"
mcp_lock_acquired=0

atomic_publish() {
  local source="$1"
  local destination="$2"
  local publish_destination="$destination"
  local publish_dir
  local staged

  if [[ -L "$destination" ]]; then
    publish_destination="$(
      node --input-type=module -e \
        'import {realpathSync} from "node:fs"; process.stdout.write(realpathSync(process.argv[1]));' \
        "$destination"
    )" || return 1
  fi
  publish_dir="$(dirname "$publish_destination")"
  staged="$(mktemp "$publish_dir/.muse-host-targets.publish.XXXXXX")" || return 1
  if ! cp -- "$source" "$staged"; then
    rm -f -- "$staged"
    return 1
  fi
  if ! mv -f -- "$staged" "$publish_destination"; then
    rm -f -- "$staged"
    return 1
  fi
}

acquire_mcp_build_lock() {
  local owner

  if mkdir -- "$mcp_lock_dir" 2>/dev/null; then
    if ! printf '%s\n' "$$" > "$mcp_lock_owner"; then
      rmdir -- "$mcp_lock_dir" 2>/dev/null || true
      fail "could not record ownership of the MCP build lock: $mcp_lock_dir"
    fi
    mcp_lock_acquired=1
    return
  fi

  owner=""
  IFS= read -r owner < "$mcp_lock_owner" 2>/dev/null || true
  if [[ "$owner" =~ ^[0-9]+$ ]] && kill -0 "$owner" 2>/dev/null; then
    fail "another MCP-producing build is active (pid $owner)"
  fi
  if [[ "$owner" =~ ^[0-9]+$ ]]; then
    fail "stale MCP build lock owned by dead pid $owner; remove $mcp_lock_dir only after verifying no build is active"
  fi
  fail "MCP build lock has no valid owner; remove $mcp_lock_dir only after verifying no build is active"
}

cleanup_mcp_registry() {
  local exit_status=$?
  local owner
  local temp
  set +e
  trap - EXIT

  if ((exit_status != 0 && mcp_state_restore_ready)); then
    if ((mcp_original_registry_present)); then
      atomic_publish "$mcp_original_registry" .mcp.json \
        || printf '[muse host build] failed to restore .mcp.json\n' >&2
    else
      rm -f -- .mcp.json \
        || printf '[muse host build] failed to remove partial .mcp.json\n' >&2
    fi
    if ((mcp_original_ownership_present)); then
      atomic_publish "$mcp_original_ownership" "$mcp_ownership_file" \
        || printf '[muse host build] failed to restore %s\n' "$mcp_ownership_file" >&2
    else
      rm -f -- "$mcp_ownership_file" \
        || printf '[muse host build] failed to remove partial %s\n' "$mcp_ownership_file" >&2
    fi
  fi

  for temp in \
    "$mcp_registry" \
    "$generated_mcp_registry" \
    "$mcp_generated_output" \
    "$mcp_ownership" \
    "$mcp_original_registry" \
    "$mcp_original_ownership"; do
    [[ -z "$temp" ]] || rm -f -- "$temp"
  done

  if ((mcp_lock_acquired)); then
    owner=""
    IFS= read -r owner < "$mcp_lock_owner" 2>/dev/null || true
    if [[ "$owner" == "$$" ]]; then
      rm -f -- "$mcp_lock_owner" \
        || printf '[muse host build] failed to remove lock owner %s\n' "$mcp_lock_owner" >&2
      rmdir -- "$mcp_lock_dir" \
        || printf '[muse host build] failed to release %s\n' "$mcp_lock_dir" >&2
    else
      printf '[muse host build] refused to remove a lock owned by pid %s\n' "$owner" >&2
    fi
  fi

  exit "$exit_status"
}

if ((mcp_target_count > 0)); then
  trap cleanup_mcp_registry EXIT
  acquire_mcp_build_lock
  mcp_registry="$(mktemp)"
  generated_mcp_registry="$(mktemp)"
  mcp_generated_output="$(mktemp)"
  mcp_ownership="$(mktemp)"
  mcp_original_registry="$(mktemp)"
  mcp_original_ownership="$(mktemp)"
  if [[ -e .mcp.json || -L .mcp.json ]]; then
    cp .mcp.json "$mcp_original_registry"
    mcp_original_registry_present=1
    cp "$mcp_original_registry" "$mcp_registry"
  else
    printf '%s\n' '{"mcpServers":{}}' > "$mcp_registry"
  fi
  if [[ -e "$mcp_ownership_file" || -L "$mcp_ownership_file" ]]; then
    cp "$mcp_ownership_file" "$mcp_original_ownership"
    mcp_original_ownership_present=1
    cp "$mcp_original_ownership" "$mcp_ownership"
  else
    printf '%s\n' '{"version":1,"targets":{}}' > "$mcp_ownership"
  fi
  mcp_state_restore_ready=1
  printf '%s\n' '{"mcpServers":{}}' > "$generated_mcp_registry"
fi

merge_mcp_registration() {
  local target="$1"
  local generated_registry="$mcp_generated_output"
  [[ -s "$generated_registry" ]] || fail "host build did not publish $generated_registry"

  node --input-type=module - \
    "$mcp_registry" \
    "$generated_registry" \
    "$generated_mcp_registry" \
    "$mcp_ownership" \
    "$target" <<'NODE'
import {readFileSync, writeFileSync} from "node:fs";
import {isDeepStrictEqual} from "node:util";

const [
  accumulatorPath,
  generatedPath,
  generatedThisRequestPath,
  ownershipPath,
  target,
] = process.argv.slice(2);

function registrations(path) {
  const value = JSON.parse(readFileSync(path, "utf8"));
  const servers = value?.mcpServers;
  if (!servers || typeof servers !== "object" || Array.isArray(servers)) {
    throw new Error(`${path} must contain an mcpServers object`);
  }
  return servers;
}

function targetOwnership(path) {
  const value = JSON.parse(readFileSync(path, "utf8"));
  const targets = value?.targets;
  if (value?.version !== 1
      || !targets
      || typeof targets !== "object"
      || Array.isArray(targets)
      || Object.values(targets).some((name) => typeof name !== "string" || name.length === 0)) {
    throw new Error(`${path} must contain a version 1 targets object of registration names`);
  }
  return targets;
}

const merged = Object.assign(Object.create(null), registrations(accumulatorPath));
const generatedThisRequest = Object.assign(
  Object.create(null),
  registrations(generatedThisRequestPath),
);
const ownership = Object.assign(Object.create(null), targetOwnership(ownershipPath));
const generatedEntries = Object.entries(registrations(generatedPath));
if (generatedEntries.length !== 1) {
  throw new Error(`${generatedPath} must contain exactly one generated MCP registration`);
}

for (const [name, registration] of generatedEntries) {
  if (Object.hasOwn(generatedThisRequest, name)
      && !isDeepStrictEqual(generatedThisRequest[name], registration)) {
    throw new Error(`conflicting MCP registration: ${name}`);
  }

  for (const [ownedTarget, ownedName] of Object.entries(ownership)) {
    if (ownedTarget !== target && ownedName === name) {
      throw new Error(`MCP registration ${name} is already owned by target ${ownedTarget}`);
    }
  }

  const previousName = ownership[target];
  if (previousName) {
    if (previousName !== name) {
      delete merged[previousName];
    }
  } else {
    // One-time adoption for registries created before the ownership sidecar.
    // Once adopted, later renames use the target key and never payload equality.
    for (const [legacyName, legacyRegistration] of Object.entries(merged)) {
      if (legacyName !== name && isDeepStrictEqual(legacyRegistration, registration)) {
        delete merged[legacyName];
      }
    }
  }

  generatedThisRequest[name] = registration;
  merged[name] = registration;
  ownership[target] = name;
}

const sorted = Object.fromEntries(Object.keys(merged).sort().map((name) => [name, merged[name]]));
const sortedGenerated = Object.fromEntries(
  Object.keys(generatedThisRequest).sort().map((name) => [name, generatedThisRequest[name]]),
);
const sortedOwnership = Object.fromEntries(
  Object.keys(ownership).sort().map((ownedTarget) => [ownedTarget, ownership[ownedTarget]]),
);
writeFileSync(accumulatorPath, `${JSON.stringify({mcpServers: sorted}, null, 2)}\n`);
writeFileSync(
  generatedThisRequestPath,
  `${JSON.stringify({mcpServers: sortedGenerated}, null, 2)}\n`,
);
writeFileSync(
  ownershipPath,
  `${JSON.stringify({version: 1, targets: sortedOwnership}, null, 2)}\n`,
);
NODE
}

build_target() {
  local target="$1"
  local generator
  local entrypoint

  case "$target" in
    opencode-plugin)
      generator="eta-mu.opencode.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/opencode_plugin.cljs"
      ;;
    mcp-server)
      generator="eta-mu.mcp.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/mcp_server.cljs"
      ;;
    claude-server)
      generator="eta-mu.claude.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/claude_server.cljs"
      ;;
  esac

  printf '[muse host build] generating %s from .ημ/config\n' "$entrypoint"
  clojure -M -e "((requiring-resolve '$generator) {})"
  [[ -s "$entrypoint" ]] || fail "generator did not write $entrypoint"

  printf '[muse host build] releasing %s\n' "$target"
  case "$target" in
    mcp-server|claude-server)
      : > "$mcp_generated_output"
      MUSE_MCP_CONFIG_OUTPUT="$mcp_generated_output" "$shadow" release "$target"
      ;;
    *)
      "$shadow" release "$target"
      ;;
  esac

  if [[ -n "$mcp_registry" ]]; then
    case "$target" in
      mcp-server|claude-server)
        merge_mcp_registration "$target"
        atomic_publish "$mcp_registry" .mcp.json
        atomic_publish "$mcp_ownership" "$mcp_ownership_file"
        ;;
    esac
  fi

  if [[ "$target" == claude-server ]]; then
    printf '[muse host build] emitting Claude hook configuration\n'
    node .claude/dist/claude-server.js --emit-hook-config
  fi
}

for target in "${targets[@]}"; do
  build_target "$target"
done
