#!/usr/bin/env bash
# Generate a host target's ignored entry namespace before Shadow discovers the
# module graph, then build it with this checkout's pinned Shadow executable.

set -euo pipefail

repo_root="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
cd "$repo_root"

usage() {
  printf 'Usage: %s <opencode-plugin|mcp-server|claude-server|all> [...]\n' "$0" >&2
}

fail() {
  printf '[muse host build] %s\n' "$*" >&2
  exit 64
}

if (($# == 0)); then
  usage
  exit 64
fi

if (($# > 1)); then
  for target in "$@"; do
    [[ "$target" != all ]] || fail "'all' cannot be combined with another target"
  done
fi

targets=("$@")
if [[ "${targets[0]}" == all ]]; then
  targets=(opencode-plugin mcp-server claude-server)
fi

# Validate the complete request before probing or invoking any build tool.
for target in "${targets[@]}"; do
  case "$target" in
    opencode-plugin|mcp-server|claude-server) ;;
    *)
      usage
      fail "unsupported target: $target"
      ;;
  esac
done

command -v clojure >/dev/null 2>&1 || fail "missing prerequisite: clojure"
command -v node >/dev/null 2>&1 || fail "missing prerequisite: node"

shadow="$repo_root/node_modules/.bin/shadow-cljs"
[[ -x "$shadow" ]] || fail "missing pinned Shadow executable; run npm ci first"

# The generic MCP and Claude hooks each own a complete one-server document, so
# every MCP-producing request must preserve registrations that are not rebuilt,
# accumulate the documents generated by this request, publish their union to
# the configured MCP destination after each build, and keep a target-to-name
# producer-and-target ownership map so a rebuilt target can retire only its
# own checkout's old registration in a registry shared by several checkouts.
mcp_target_count=0
for target in "${targets[@]}"; do
  case "$target" in
    mcp-server|claude-server)
      mcp_target_count=$((mcp_target_count + 1))
      ;;
  esac
done

mcp_registry=""
generated_mcp_registry=""
mcp_generated_output=""
mcp_ownership=""
mcp_original_registry=""
mcp_original_ownership=""
mcp_original_registry_present=0
mcp_original_ownership_present=0
mcp_state_restore_ready=0
mcp_public_registry=""
mcp_producer_id=""
mcp_producer_file="$repo_root/.muse-host-targets-producer-id"
mcp_ownership_file=""
mcp_lock_dir=""
mcp_lock_owner=""
mcp_lock_acquired=0
mcp_transaction_file=""
mcp_transaction_record=""
mcp_recovery_registry=""
mcp_recovery_ownership=""

atomic_publish() {
  local source="$1"
  local destination="$2"
  local new_mode="${3-}"
  local publish_destination="$destination"
  local publish_dir
  local staged

  if [[ -L "$destination" ]]; then
    publish_destination="$(
      node --input-type=module -e \
        'import {realpathSync} from "node:fs"; process.stdout.write(realpathSync(process.argv[1]));' \
        "$destination"
    )" || return 1
  fi
  publish_dir="$(dirname "$publish_destination")"
  staged="$(mktemp "$publish_dir/.muse-host-targets.publish.XXXXXX")" || return 1
  if ! cp -- "$source" "$staged"; then
    rm -f -- "$staged"
    return 1
  fi
  if [[ -e "$publish_destination" ]]; then
    if ! node --input-type=module - "$publish_destination" <<'NODE'
import {statSync} from "node:fs";

const [destination] = process.argv.slice(2);
const existing = statSync(destination);
const uid = process.getuid();
if (existing.uid !== uid) {
  throw new Error(`${destination} changed to cross-user ownership after preflight`);
}
if (existing.gid !== process.getgid() && !process.getgroups().includes(existing.gid)) {
  throw new Error(`${destination} changed to an unavailable group after preflight`);
}
NODE
    then
      rm -f -- "$staged"
      return 1
    fi
    if ! cp --attributes-only --preserve=all --no-preserve=timestamps \
      -- "$publish_destination" "$staged"; then
      rm -f -- "$staged"
      return 1
    fi
  elif ! node --input-type=module - "$staged" "$new_mode" <<'NODE'
import {chmodSync} from "node:fs";

const [staged, requestedMode] = process.argv.slice(2);
const mode = requestedMode.length > 0
  ? Number.parseInt(requestedMode, 8)
  : 0o666 & ~process.umask();
if (!Number.isInteger(mode)) throw new Error(`invalid staged mode: ${requestedMode}`);
chmodSync(staged, mode);
NODE
  then
    rm -f -- "$staged"
    return 1
  fi
  if ! sync -f -- "$staged"; then
    rm -f -- "$staged"
    return 1
  fi
  if ! mv -f -- "$staged" "$publish_destination"; then
    rm -f -- "$staged"
    return 1
  fi
  sync -f -- "$publish_dir"
}

canonicalize_mcp_destination() {
  local configured="$1"

  mkdir -p -- "$(dirname "$configured")"
  node --input-type=module - "$configured" <<'NODE'
import {lstatSync, realpathSync} from "node:fs";
import {basename, dirname, join, resolve} from "node:path";

const [configured] = process.argv.slice(2);
const absolute = resolve(configured);
const existing = lstatSync(absolute, {throwIfNoEntry: false});
if (existing) {
  process.stdout.write(realpathSync(absolute));
} else {
  process.stdout.write(join(realpathSync(dirname(absolute)), basename(absolute)));
}
NODE
}

resolve_mcp_producer_identity() {
  node --input-type=module - "$mcp_producer_file" "$repo_root" <<'NODE'
import {randomBytes} from "node:crypto";
import {
  chmodSync,
  closeSync,
  fsyncSync,
  linkSync,
  lstatSync,
  openSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";

const [identityPath, root] = process.argv.slice(2);
const temporaryPath = `${identityPath}.${process.pid}.${randomBytes(8).toString("hex")}.tmp`;

function readIdentity() {
  const metadata = lstatSync(identityPath, {throwIfNoEntry: false});
  if (!metadata) return null;
  if (!metadata.isFile() || metadata.isSymbolicLink()) {
    throw new Error(`${identityPath} is not a regular identity file`);
  }
  if (metadata.uid !== process.getuid()) {
    throw new Error(`${identityPath} is owned by uid ${metadata.uid}`);
  }
  if ((metadata.mode & 0o777) !== 0o600) {
    throw new Error(`${identityPath} must use mode 0600`);
  }
  const value = readFileSync(identityPath, "utf8");
  if (!/^[0-9a-f]{64}\n$/.test(value) || /^0{64}\n$/.test(value)) {
    throw new Error(`${identityPath} does not contain one valid producer identity`);
  }
  return value.slice(0, -1);
}

let identity = readIdentity();
if (!identity) {
  try {
    let generated;
    do {
      generated = randomBytes(32).toString("hex");
    } while (/^0{64}$/.test(generated));
    writeFileSync(temporaryPath, `${generated}\n`, {
      flag: "wx",
      mode: 0o600,
    });
    chmodSync(temporaryPath, 0o600);
    const temporary = openSync(temporaryPath, "r");
    try {
      fsyncSync(temporary);
    } finally {
      closeSync(temporary);
    }
    try {
      linkSync(temporaryPath, identityPath);
    } catch (error) {
      if (error?.code !== "EEXIST") throw error;
    }
  } finally {
    try {
      unlinkSync(temporaryPath);
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
  }
  identity = readIdentity();
}
const directory = openSync(root, "r");
try {
  fsyncSync(directory);
} finally {
  closeSync(directory);
}
process.stdout.write(identity);
NODE
}

resolve_mcp_public_registry() {
  local configured
  local registry_dir
  local resolved
  local resolver
  local target

  for target in "${targets[@]}"; do
    case "$target" in
      mcp-server)
        resolver="eta-mu.mcp.build/mcp-config-path"
        ;;
      claude-server)
        resolver="eta-mu.claude.build/mcp-config-path"
        ;;
      *)
        continue
        ;;
    esac

    configured="$(clojure -M -e "(print ((requiring-resolve '$resolver)))")"
    [[ -n "$configured" ]] || fail "$target does not configure :publish :mcp-config"
    [[ "$configured" != *$'\n'* ]] || fail "$target configured an invalid multiline MCP destination"
    resolved="$(canonicalize_mcp_destination "$configured")"
    if [[ -z "$mcp_public_registry" ]]; then
      mcp_public_registry="$resolved"
    elif [[ "$resolved" != "$mcp_public_registry" ]]; then
      fail "MCP-producing targets configure different canonical destinations: $mcp_public_registry and $resolved"
    fi
  done

  [[ -n "$mcp_public_registry" ]] || fail "could not resolve the configured MCP destination"
  if [[ "${mcp_public_registry##*/}" == .mcp.json ]]; then
    registry_dir="${mcp_public_registry%/*}"
    mcp_ownership_file="$registry_dir/.muse-host-targets-owners.json"
    mcp_lock_dir="$registry_dir/.muse-host-targets.lock"
    mcp_transaction_file="$registry_dir/.muse-host-targets-transaction.json"
  else
    mcp_ownership_file="$mcp_public_registry.muse-host-targets-owners.json"
    mcp_lock_dir="$mcp_public_registry.muse-host-targets.lock"
    mcp_transaction_file="$mcp_public_registry.muse-host-targets-transaction.json"
  fi
  mcp_lock_owner="$mcp_lock_dir/owner"
}

preflight_publish_destination() {
  local destination="$1"
  local destination_dir

  destination_dir="$(dirname "$destination")"
  mkdir -p -- "$destination_dir"
  node --input-type=module - "$destination" <<'NODE'
import {
  accessSync,
  constants,
  lstatSync,
  realpathSync,
  statSync,
} from "node:fs";
import {dirname} from "node:path";

const [destination] = process.argv.slice(2);
const link = lstatSync(destination, {throwIfNoEntry: false});
const resolved = link?.isSymbolicLink() ? realpathSync(destination) : destination;
accessSync(dirname(resolved), constants.W_OK);
const existing = lstatSync(resolved, {throwIfNoEntry: false});
if (existing) {
  const metadata = statSync(resolved);
  const uid = process.getuid();
  if (metadata.uid !== uid) {
    throw new Error(`${destination} is owned by uid ${metadata.uid}; current uid is ${uid}`);
  }
  if (metadata.gid !== process.getgid() && !process.getgroups().includes(metadata.gid)) {
    throw new Error(`${destination} uses unavailable gid ${metadata.gid}`);
  }
}
NODE
}

# Registry bytes are visible to MCP clients, while ownership is private writer
# state. Persist and fsync the complete intended pair before changing either;
# an interrupted writer leaves the marker for idempotent replay under the same
# destination-wide lock. Rollback replaces that intent before restoring bytes.
prepare_mcp_transaction() {
  local registry_source="$1"
  local registry_present="$2"
  local ownership_source="$3"
  local ownership_present="$4"

  if [[ -L "$mcp_transaction_file" \
        || (-e "$mcp_transaction_file" && ! -f "$mcp_transaction_file") ]]; then
    return 1
  fi
  [[ -z "$mcp_transaction_record" ]] || rm -f -- "$mcp_transaction_record"
  mcp_transaction_record="$(mktemp)" || return 1
  if ! node --input-type=module - \
    "$mcp_transaction_record" \
    "$registry_source" \
    "$registry_present" \
    "$ownership_source" \
    "$ownership_present" <<'NODE'
import {createHash} from "node:crypto";
import {readFileSync, writeFileSync} from "node:fs";

const [output, registryPath, registryPresent, ownershipPath, ownershipPresent] =
  process.argv.slice(2);

function capture(path, present) {
  if (present === "0") return {present: false, sha256: null, bytes: null};
  if (present !== "1") throw new Error(`invalid transaction presence flag: ${present}`);
  const bytes = readFileSync(path);
  return {
    present: true,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    bytes: bytes.toString("base64"),
  };
}

const transaction = {
  version: 1,
  registry: capture(registryPath, registryPresent),
  ownership: capture(ownershipPath, ownershipPresent),
};
writeFileSync(output, `${JSON.stringify(transaction)}\n`, {mode: 0o600});
NODE
  then
    return 1
  fi
  if ! atomic_publish "$mcp_transaction_record" "$mcp_transaction_file" 600; then
    return 1
  fi
  rm -f -- "$mcp_transaction_record"
  mcp_transaction_record=""
}

publish_or_remove() {
  local source="$1"
  local present="$2"
  local destination="$3"

  case "$present" in
    1)
      atomic_publish "$source" "$destination"
      ;;
    0)
      rm -f -- "$destination" && sync -f -- "$(dirname "$destination")"
      ;;
    *)
      return 1
      ;;
  esac
}

clear_mcp_transaction() {
  [[ -e "$mcp_transaction_file" || -L "$mcp_transaction_file" ]] || return 0
  [[ -f "$mcp_transaction_file" && ! -L "$mcp_transaction_file" ]] || return 1
  rm -f -- "$mcp_transaction_file" \
    && sync -f -- "$(dirname "$mcp_transaction_file")"
}

apply_mcp_transaction() {
  local registry_source="$1"
  local registry_present="$2"
  local ownership_source="$3"
  local ownership_present="$4"
  local order="$5"

  case "$order" in
    registry-first)
      publish_or_remove "$registry_source" "$registry_present" "$mcp_public_registry" \
        && publish_or_remove "$ownership_source" "$ownership_present" "$mcp_ownership_file"
      ;;
    ownership-first)
      publish_or_remove "$ownership_source" "$ownership_present" "$mcp_ownership_file" \
        && publish_or_remove "$registry_source" "$registry_present" "$mcp_public_registry"
      ;;
    *)
      return 1
      ;;
  esac
}

recover_mcp_transaction() {
  local ownership_present
  local registry_present
  local state

  [[ -e "$mcp_transaction_file" || -L "$mcp_transaction_file" ]] || return 0
  [[ -f "$mcp_transaction_file" && ! -L "$mcp_transaction_file" ]] \
    || fail "MCP transaction marker is not a regular file: $mcp_transaction_file"
  mcp_recovery_registry="$(mktemp)" \
    || fail "could not allocate MCP transaction recovery storage"
  mcp_recovery_ownership="$(mktemp)" \
    || fail "could not allocate MCP transaction recovery storage"
  if ! state="$(node --input-type=module - \
    "$mcp_transaction_file" \
    "$mcp_recovery_registry" \
    "$mcp_recovery_ownership" <<'NODE'
import {createHash} from "node:crypto";
import {readFileSync, writeFileSync} from "node:fs";

const [transactionPath, registryOutput, ownershipOutput] = process.argv.slice(2);
const transaction = JSON.parse(readFileSync(transactionPath, "utf8"));
if (transaction?.version !== 1) throw new Error("unsupported MCP transaction version");

function objectMap(value) {
  return value && typeof value === "object" && !Array.isArray(value);
}

function decode(label, state, output) {
  if (!objectMap(state) || typeof state.present !== "boolean") {
    throw new Error(`invalid ${label} transaction state`);
  }
  if (!state.present) {
    if (state.bytes !== null || state.sha256 !== null) {
      throw new Error(`invalid absent ${label} transaction state`);
    }
    return false;
  }
  if (typeof state.bytes !== "string" || typeof state.sha256 !== "string") {
    throw new Error(`invalid present ${label} transaction state`);
  }
  const bytes = Buffer.from(state.bytes, "base64");
  if (bytes.toString("base64") !== state.bytes) {
    throw new Error(`non-canonical ${label} transaction bytes`);
  }
  if (createHash("sha256").update(bytes).digest("hex") !== state.sha256) {
    throw new Error(`${label} transaction checksum mismatch`);
  }
  const value = JSON.parse(bytes.toString("utf8"));
  if (label === "registry") {
    if (!objectMap(value?.mcpServers)) {
      throw new Error("transaction registry must contain an mcpServers object");
    }
  } else {
    const targets = value?.targets;
    const valuesValid = objectMap(targets) && Object.values(targets).every(
      (name) => typeof name === "string" && name.length > 0,
    ) && new Set(Object.values(targets)).size === Object.values(targets).length;
    const keysValid = value?.version === 1
      ? Object.keys(targets ?? {}).every(
        (target) => /^[a-z0-9][a-z0-9-]*$/.test(target),
      )
      : value?.version === 2
        && Object.keys(targets ?? {}).every(
          (target) => /^[0-9a-f]{64}:[a-z0-9][a-z0-9-]*$/.test(target),
        );
    if (!valuesValid || !keysValid) {
      throw new Error("transaction ownership must contain a supported versioned targets object");
    }
  }
  writeFileSync(output, bytes, {mode: 0o600});
  return true;
}

const registryPresent = decode(
  "registry",
  transaction.registry,
  registryOutput,
);
const ownershipPresent = decode(
  "ownership",
  transaction.ownership,
  ownershipOutput,
);
process.stdout.write(`${registryPresent ? 1 : 0} ${ownershipPresent ? 1 : 0}`);
NODE
  )"; then
    fail "MCP transaction marker is invalid; preserve it for recovery: $mcp_transaction_file"
  fi
  read -r registry_present ownership_present <<< "$state"
  printf '[muse host build] recovering interrupted MCP state transaction\n'
  apply_mcp_transaction \
    "$mcp_recovery_registry" \
    "$registry_present" \
    "$mcp_recovery_ownership" \
    "$ownership_present" \
    registry-first \
    || fail "could not recover interrupted MCP state transaction"
  clear_mcp_transaction \
    || fail "could not clear recovered MCP transaction marker: $mcp_transaction_file"
}

publish_mcp_state() {
  prepare_mcp_transaction "$mcp_registry" 1 "$mcp_ownership" 1 \
    || fail "could not prepare MCP state transaction"
  apply_mcp_transaction "$mcp_registry" 1 "$mcp_ownership" 1 registry-first \
    || fail "could not publish MCP state transaction"
  clear_mcp_transaction \
    || fail "could not clear completed MCP transaction marker: $mcp_transaction_file"
}

acquire_mcp_build_lock() {
  local attempt
  local owner

  if mkdir -- "$mcp_lock_dir" 2>/dev/null; then
    if ! printf '%s\n' "$$" > "$mcp_lock_owner"; then
      rmdir -- "$mcp_lock_dir" 2>/dev/null || true
      fail "could not record ownership of the MCP build lock: $mcp_lock_dir"
    fi
    mcp_lock_acquired=1
    return
  fi

  [[ -d "$mcp_lock_dir" ]] || fail "could not create the MCP build lock: $mcp_lock_dir"
  owner=""
  for ((attempt = 1; attempt <= 5; attempt++)); do
    IFS= read -r owner < "$mcp_lock_owner" 2>/dev/null || true
    [[ -n "$owner" ]] && break
    sleep 0.05
  done
  if [[ "$owner" =~ ^[0-9]+$ ]] && kill -0 "$owner" 2>/dev/null; then
    fail "another MCP-producing build is active (pid $owner)"
  fi
  if [[ "$owner" =~ ^[0-9]+$ ]]; then
    fail "stale MCP build lock owned by dead pid $owner; remove $mcp_lock_dir only after verifying no build is active"
  fi
  fail "MCP build lock has no valid owner; remove $mcp_lock_dir only after verifying no build is active"
}

cleanup_mcp_registry() {
  local exit_status=$?
  local owner
  local registry_restored=0
  local rollback_prepared=0
  local ownership_restored=0
  local temp
  set +e
  trap - EXIT

  if ((exit_status != 0 && mcp_state_restore_ready)); then
    if prepare_mcp_transaction \
      "$mcp_original_registry" \
      "$mcp_original_registry_present" \
      "$mcp_original_ownership" \
      "$mcp_original_ownership_present"; then
      rollback_prepared=1
    else
      printf '[muse host build] failed to prepare MCP rollback transaction\n' >&2
    fi

    if ((rollback_prepared)); then
      if publish_or_remove \
        "$mcp_original_ownership" \
        "$mcp_original_ownership_present" \
        "$mcp_ownership_file"; then
        ownership_restored=1
      else
        if ((mcp_original_ownership_present)); then
          printf '[muse host build] failed to restore %s\n' "$mcp_ownership_file" >&2
        else
          printf '[muse host build] failed to remove partial %s\n' "$mcp_ownership_file" >&2
        fi
      fi

      if ((ownership_restored)); then
        if publish_or_remove \
          "$mcp_original_registry" \
          "$mcp_original_registry_present" \
          "$mcp_public_registry"; then
          registry_restored=1
        elif ((mcp_original_registry_present)); then
          printf '[muse host build] failed to restore %s\n' "$mcp_public_registry" >&2
        else
          printf '[muse host build] failed to remove partial %s\n' "$mcp_public_registry" >&2
        fi
      else
        printf '[muse host build] skipped registry rollback because ownership rollback failed\n' >&2
      fi

      if ((ownership_restored && registry_restored)); then
        clear_mcp_transaction \
          || printf '[muse host build] failed to clear completed MCP rollback transaction\n' >&2
      else
        printf '[muse host build] preserved MCP rollback transaction for recovery: %s\n' \
          "$mcp_transaction_file" >&2
      fi
    fi
  fi

  for temp in \
    "$mcp_registry" \
    "$generated_mcp_registry" \
    "$mcp_generated_output" \
    "$mcp_ownership" \
    "$mcp_original_registry" \
    "$mcp_original_ownership" \
    "$mcp_transaction_record" \
    "$mcp_recovery_registry" \
    "$mcp_recovery_ownership"; do
    [[ -z "$temp" ]] || rm -f -- "$temp"
  done

  if ((mcp_lock_acquired)); then
    owner=""
    IFS= read -r owner < "$mcp_lock_owner" 2>/dev/null || true
    if [[ "$owner" == "$$" ]]; then
      rm -f -- "$mcp_lock_owner" \
        || printf '[muse host build] failed to remove lock owner %s\n' "$mcp_lock_owner" >&2
      rmdir -- "$mcp_lock_dir" \
        || printf '[muse host build] failed to release %s\n' "$mcp_lock_dir" >&2
    else
      printf '[muse host build] refused to remove a lock owned by pid %s\n' "$owner" >&2
    fi
  fi

  exit "$exit_status"
}

if ((mcp_target_count > 0)); then
  # One private, durable token follows the checkout when its root moves.
  # Physical path aliases read the same file, while separate checkouts create
  # distinct ownership keys even when they publish to one shared registry.
  mcp_producer_id="$(resolve_mcp_producer_identity)" \
    || fail "could not resolve the stable MCP producer identity"
  resolve_mcp_public_registry
  trap cleanup_mcp_registry EXIT
  acquire_mcp_build_lock
  preflight_publish_destination "$mcp_public_registry" \
    || fail "configured MCP destination failed ownership/write preflight: $mcp_public_registry"
  preflight_publish_destination "$mcp_ownership_file" \
    || fail "MCP ownership destination failed ownership/write preflight: $mcp_ownership_file"
  preflight_publish_destination "$mcp_transaction_file" \
    || fail "MCP transaction destination failed ownership/write preflight: $mcp_transaction_file"
  recover_mcp_transaction
  mcp_registry="$(mktemp)"
  generated_mcp_registry="$(mktemp)"
  mcp_generated_output="$(mktemp)"
  mcp_ownership="$(mktemp)"
  mcp_original_registry="$(mktemp)"
  mcp_original_ownership="$(mktemp)"
  if [[ -e "$mcp_public_registry" || -L "$mcp_public_registry" ]]; then
    cp "$mcp_public_registry" "$mcp_original_registry"
    mcp_original_registry_present=1
    cp "$mcp_original_registry" "$mcp_registry"
  else
    printf '%s\n' '{"mcpServers":{}}' > "$mcp_registry"
  fi
  if [[ -e "$mcp_ownership_file" || -L "$mcp_ownership_file" ]]; then
    cp "$mcp_ownership_file" "$mcp_original_ownership"
    mcp_original_ownership_present=1
    cp "$mcp_original_ownership" "$mcp_ownership"
  else
    printf '%s\n' '{"version":1,"targets":{}}' > "$mcp_ownership"
  fi
  mcp_state_restore_ready=1
  printf '%s\n' '{"mcpServers":{}}' > "$generated_mcp_registry"
fi

merge_mcp_registration() {
  local target="$1"
  local generated_registry="$mcp_generated_output"
  [[ -s "$generated_registry" ]] || fail "host build did not publish $generated_registry"

  node --input-type=module - \
    "$mcp_registry" \
    "$generated_registry" \
    "$generated_mcp_registry" \
    "$mcp_ownership" \
    "$target" \
    "$mcp_producer_id" <<'NODE'
import {readFileSync, writeFileSync} from "node:fs";
import {isDeepStrictEqual} from "node:util";

const [
  accumulatorPath,
  generatedPath,
  generatedThisRequestPath,
  ownershipPath,
  target,
  producerId,
] = process.argv.slice(2);
const legacyProducerId = "0".repeat(64);

function registrations(path) {
  const value = JSON.parse(readFileSync(path, "utf8"));
  const servers = value?.mcpServers;
  if (!servers || typeof servers !== "object" || Array.isArray(servers)) {
    throw new Error(`${path} must contain an mcpServers object`);
  }
  return servers;
}

function targetOwnership(path) {
  const value = JSON.parse(readFileSync(path, "utf8"));
  const targets = value?.targets;
  if (!targets
      || typeof targets !== "object"
      || Array.isArray(targets)
      || Object.values(targets).some((name) => typeof name !== "string" || name.length === 0)
      || new Set(Object.values(targets)).size !== Object.values(targets).length) {
    throw new Error(`${path} must contain a supported versioned targets object`);
  }
  if (value?.version === 1) {
    if (Object.keys(targets).some(
      (ownedTarget) => !/^[a-z0-9][a-z0-9-]*$/.test(ownedTarget),
    )) {
      throw new Error(`${path} contains an invalid legacy target key`);
    }
    return Object.fromEntries(
      Object.entries(targets).map(
        ([ownedTarget, name]) => [`${legacyProducerId}:${ownedTarget}`, name],
      ),
    );
  }
  if (value?.version !== 2
      || Object.keys(targets).some(
        (ownedTarget) => !/^[0-9a-f]{64}:[a-z0-9][a-z0-9-]*$/.test(ownedTarget),
      )) {
    throw new Error(`${path} must contain a supported versioned targets object`);
  }
  return targets;
}

if (!/^[0-9a-f]{64}$/.test(producerId) || producerId === legacyProducerId) {
  throw new Error(`invalid MCP producer identity: ${producerId}`);
}

const merged = Object.assign(Object.create(null), registrations(accumulatorPath));
const generatedThisRequest = Object.assign(
  Object.create(null),
  registrations(generatedThisRequestPath),
);
const ownership = Object.assign(
  Object.create(null),
  targetOwnership(ownershipPath),
);
const generatedEntries = Object.entries(registrations(generatedPath));
if (generatedEntries.length !== 1) {
  throw new Error(`${generatedPath} must contain exactly one generated MCP registration`);
}

for (const [name, registration] of generatedEntries) {
  if (Object.hasOwn(generatedThisRequest, name)
      && !isDeepStrictEqual(generatedThisRequest[name], registration)) {
    throw new Error(`conflicting MCP registration: ${name}`);
  }

  const ownershipKey = `${producerId}:${target}`;
  const legacyOwnershipKey = `${legacyProducerId}:${target}`;
  for (const [ownedTarget, ownedName] of Object.entries(ownership)) {
    if (ownedTarget !== ownershipKey && ownedName === name) {
      if (ownedTarget === legacyOwnershipKey) {
        delete ownership[ownedTarget];
      } else {
        throw new Error(`MCP registration ${name} is already owned by producer target ${ownedTarget}`);
      }
    }
  }

  const previousName = ownership[ownershipKey];
  if (previousName) {
    if (previousName !== name) {
      delete merged[previousName];
    }
  }

  generatedThisRequest[name] = registration;
  merged[name] = registration;
  ownership[ownershipKey] = name;
}

const sorted = Object.fromEntries(Object.keys(merged).sort().map((name) => [name, merged[name]]));
const sortedGenerated = Object.fromEntries(
  Object.keys(generatedThisRequest).sort().map((name) => [name, generatedThisRequest[name]]),
);
const sortedOwnership = Object.fromEntries(
  Object.keys(ownership).sort().map((ownedTarget) => [ownedTarget, ownership[ownedTarget]]),
);
writeFileSync(accumulatorPath, `${JSON.stringify({mcpServers: sorted}, null, 2)}\n`);
writeFileSync(
  generatedThisRequestPath,
  `${JSON.stringify({mcpServers: sortedGenerated}, null, 2)}\n`,
);
writeFileSync(
  ownershipPath,
  `${JSON.stringify({version: 2, targets: sortedOwnership}, null, 2)}\n`,
);
NODE
}

build_target() {
  local target="$1"
  local generator
  local entrypoint

  case "$target" in
    opencode-plugin)
      generator="eta-mu.opencode.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/opencode_plugin.cljs"
      ;;
    mcp-server)
      generator="eta-mu.mcp.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/mcp_server.cljs"
      ;;
    claude-server)
      generator="eta-mu.claude.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/claude_server.cljs"
      ;;
  esac

  printf '[muse host build] generating %s from .ημ/config\n' "$entrypoint"
  clojure -M -e "((requiring-resolve '$generator) {})"
  [[ -s "$entrypoint" ]] || fail "generator did not write $entrypoint"

  printf '[muse host build] releasing %s\n' "$target"
  case "$target" in
    mcp-server|claude-server)
      : > "$mcp_generated_output"
      MUSE_MCP_CONFIG_OUTPUT="$mcp_generated_output" "$shadow" release "$target"
      ;;
    *)
      "$shadow" release "$target"
      ;;
  esac

  if [[ -n "$mcp_registry" ]]; then
    case "$target" in
      mcp-server|claude-server)
        merge_mcp_registration "$target"
        publish_mcp_state
        ;;
    esac
  fi

  if [[ "$target" == claude-server ]]; then
    printf '[muse host build] emitting Claude hook configuration\n'
    node .claude/dist/claude-server.js --emit-hook-config
  fi
}

for target in "${targets[@]}"; do
  build_target "$target"
done
