#!/usr/bin/env bash
# Generate a host target's ignored entry namespace before Shadow discovers the
# module graph, then build it with this checkout's pinned Shadow executable.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

usage() {
  printf 'Usage: %s <opencode-plugin|mcp-server|claude-server|all> [...]\n' "$0" >&2
}

fail() {
  printf '[muse host build] %s\n' "$*" >&2
  exit 64
}

if (($# == 0)); then
  usage
  exit 64
fi

if (($# > 1)); then
  for target in "$@"; do
    [[ "$target" != all ]] || fail "'all' cannot be combined with another target"
  done
fi

targets=("$@")
if [[ "${targets[0]}" == all ]]; then
  targets=(opencode-plugin mcp-server claude-server)
fi

# Validate the complete request before probing or invoking any build tool.
for target in "${targets[@]}"; do
  case "$target" in
    opencode-plugin|mcp-server|claude-server) ;;
    *)
      usage
      fail "unsupported target: $target"
      ;;
  esac
done

command -v clojure >/dev/null 2>&1 || fail "missing prerequisite: clojure"
command -v node >/dev/null 2>&1 || fail "missing prerequisite: node"

shadow="$repo_root/node_modules/.bin/shadow-cljs"
[[ -x "$shadow" ]] || fail "missing pinned Shadow executable; run npm ci first"

# The generic MCP and Claude targets both publish to .mcp.json. Their build
# hooks each own a complete one-server document, so every MCP-producing request
# must preserve registrations that are not rebuilt, accumulate the documents
# generated by this request, and publish their union after all builds finish.
mcp_target_count=0
for target in "${targets[@]}"; do
  case "$target" in
    mcp-server|claude-server)
      mcp_target_count=$((mcp_target_count + 1))
      ;;
  esac
done

mcp_registry=""
generated_mcp_registry=""
if ((mcp_target_count > 0)); then
  mcp_registry="$(mktemp)"
  generated_mcp_registry="$(mktemp)"
  if [[ -e .mcp.json ]]; then
    cp .mcp.json "$mcp_registry"
  else
    printf '%s\n' '{"mcpServers":{}}' > "$mcp_registry"
  fi
  printf '%s\n' '{"mcpServers":{}}' > "$generated_mcp_registry"
  trap 'rm -f -- "$mcp_registry" "$generated_mcp_registry"' EXIT
fi

merge_mcp_registration() {
  local generated_registry=".mcp.json"
  [[ -s "$generated_registry" ]] || fail "host build did not publish $generated_registry"

  node --input-type=module - \
    "$mcp_registry" "$generated_registry" "$generated_mcp_registry" <<'NODE'
import {readFileSync, writeFileSync} from "node:fs";

const [accumulatorPath, generatedPath, generatedThisRequestPath] = process.argv.slice(2);

function registrations(path) {
  const value = JSON.parse(readFileSync(path, "utf8"));
  const servers = value?.mcpServers;
  if (!servers || typeof servers !== "object" || Array.isArray(servers)) {
    throw new Error(`${path} must contain an mcpServers object`);
  }
  return servers;
}

const merged = {...registrations(accumulatorPath)};
const generatedThisRequest = {...registrations(generatedThisRequestPath)};
for (const [name, registration] of Object.entries(registrations(generatedPath))) {
  if (name in generatedThisRequest
      && JSON.stringify(generatedThisRequest[name]) !== JSON.stringify(registration)) {
    throw new Error(`conflicting MCP registration: ${name}`);
  }
  generatedThisRequest[name] = registration;
  merged[name] = registration;
}

const sorted = Object.fromEntries(Object.keys(merged).sort().map((name) => [name, merged[name]]));
const sortedGenerated = Object.fromEntries(
  Object.keys(generatedThisRequest).sort().map((name) => [name, generatedThisRequest[name]]),
);
writeFileSync(accumulatorPath, `${JSON.stringify({mcpServers: sorted}, null, 2)}\n`);
writeFileSync(
  generatedThisRequestPath,
  `${JSON.stringify({mcpServers: sortedGenerated}, null, 2)}\n`,
);
NODE
}

build_target() {
  local target="$1"
  local generator
  local entrypoint

  case "$target" in
    opencode-plugin)
      generator="eta-mu.opencode.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/opencode_plugin.cljs"
      ;;
    mcp-server)
      generator="eta-mu.mcp.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/mcp_server.cljs"
      ;;
    claude-server)
      generator="eta-mu.claude.build/generate-entrypoint"
      entrypoint="src/gen/eta_mu/gen/claude_server.cljs"
      ;;
  esac

  printf '[muse host build] generating %s from .ημ/config\n' "$entrypoint"
  clojure -M -e "((requiring-resolve '$generator) {})"
  [[ -s "$entrypoint" ]] || fail "generator did not write $entrypoint"

  printf '[muse host build] releasing %s\n' "$target"
  "$shadow" release "$target"

  if [[ "$target" == claude-server ]]; then
    printf '[muse host build] emitting Claude hook configuration\n'
    node .claude/dist/claude-server.js --emit-hook-config
  fi

  if [[ -n "$mcp_registry" ]]; then
    case "$target" in
      mcp-server|claude-server) merge_mcp_registration ;;
    esac
  fi
}

for target in "${targets[@]}"; do
  build_target "$target"
done

if [[ -n "$mcp_registry" ]]; then
  cp "$mcp_registry" .mcp.json
fi
