(ns eta-mu.opencode.settings
  "Pure rendering of :settings fragments into the host's JSON(C) config.

   A settings fragment carries host configuration verbatim as EDN:

     {:settings {:model \"kimi-for-coding/kimi-k2.7\"
                 :permission {:external_directory {\"~/devel/**\" :allow}}}}

   Fragments deep-merge in import order (later wins), keyword keys and
   values become strings, and the result renders deterministically:
   top-level keys in the host's conventional order, nested keys sorted.
   No I/O — the daemon supplies fragments and writes the output."
  (:require [clojure.string :as str]))

;; ---------------------------------------------------------------------------
;; Merging
;; ---------------------------------------------------------------------------

(defn deep-merge
  "Recursive merge where maps merge and anything else replaces."
  [a b]
  (if (and (map? a) (map? b))
    (merge-with deep-merge a b)
    b))

(defn merged
  "Deep merge of settings fragments in order (later wins)."
  [fragments]
  (reduce deep-merge {} fragments))

;; ---------------------------------------------------------------------------
;; Deterministic JSON rendering
;; ---------------------------------------------------------------------------

(def top-level-order
  "The host's conventional top-level key order; unknown keys follow,
   sorted."
  ["$schema" "theme" "model" "small_model" "username" "instructions"
   "skills" "permission" "snapshot" "share" "lsp" "autoupdate"
   "provider" "mcp" "plugin" "agent" "command" "keybinds" "tui"
   "server" "experimental"])

(defn json-key [k]
  (if (keyword? k) (name k) (str k)))

(defn- key-comparator [order]
  (let [rank (zipmap order (range))]
    (fn [a b]
      (let [ra (get rank a) rb (get rank b)]
        (cond
          (and ra rb) (compare ra rb)
          ra          -1
          rb          1
          :else       (compare a b))))))

(defn- escape [s]
  (-> s
      (str/replace "\\" "\\\\")
      (str/replace "\"" "\\\"")
      (str/replace "\n" "\\n")
      (str/replace "\r" "\\r")
      (str/replace "\t" "\\t")))

(defn- json-str [s]
  (str "\"" (escape s) "\""))

(defn render-value
  "Render one EDN value as JSON. `depth` 0 uses top-level-order for map
   keys; deeper maps sort alphabetically. Keywords render as their name."
  ([value] (render-value value 0))
  ([value depth]
   (let [pad  (apply str (repeat (* 2 depth) " "))
         pad+ (str pad "  ")]
     (cond
       (map? value)
       (if (empty? value)
         "{}"
         (let [ks (sort (key-comparator (if (zero? depth) top-level-order []))
                        (map json-key (keys value)))
               by-name (into {} (map (fn [[k v]] [(json-key k) v])) value)]
           (str "{\n"
                (str/join ",\n"
                          (for [k ks]
                            (str pad+ (json-str k) ": "
                                 (render-value (get by-name k) (inc depth)))))
                "\n" pad "}")))

       (sequential? value)
       (if (empty? value)
         "[]"
         (str "[\n"
              (str/join ",\n"
                        (map #(str pad+ (render-value % (inc depth))) value))
              "\n" pad "]"))

       (string? value)  (json-str value)
       (keyword? value) (json-str (name value))
       (nil? value)     "null"
       :else            (str value)))))

(defn render-jsonc
  "Render merged settings as a JSONC document with a provenance header."
  [settings {:keys [source]}]
  (str "// Generated by the eta-mu daemon"
       (when source (str " from " source))
       " — do not edit.\n"
       (render-value settings 0)
       "\n"))
